module.exports = [

    // {
    // title: '축제명',
    // startDate: '축제 시작 날짜 ex) 2026-07-01',
    // endDate: '축제 끝나는 날짜 ex) 2026-08-09',
    // place: '위치(주소등)',
    // image: '이미지 주소 복붙',
    // homepage: '홈페이지주소',
    // category: '카테고리(행사, 공연, 축제 중 하나 적기)',
    // sponsor1: '주최',
    // sponsor2: '주관',
    // playTime: '축제시간',
    // useFee: '가격',
    // program: '축제에서 할수있는 활동(프로그램)',
    // summary: '축제 설명'
    // },
 {
    title: '포켓몬 메가페스타 2026 in 부산 「느긋느긋 바캉스」',
    startDate: '2026-07-17',
    endDate: '2026-08-09',
    place: '부산역, 범내골역, 전포역, 광안역, 센텀시티역, 명지 환승센터, 해운대 환승센터, 영도 국립해양박물관 정류소, 롯데백화점 부산본점 등',
    image: 'https://www.visitbusan.net/upload_data/board_data/BBS_0000009/178304490764355.png',
    homepage: 'https://pokemonkorea.co.kr/megafesta2026inbusan/menu757',
    category: '행사',
    sponsor1: '포켓몬코리아',
    sponsor2: '부산교통공사, 부산시설공단, 부산버스운송사업조합, BEXCO, 롯데백화점 부산본점 등',
    playTime: '평일 10:30~20:00 / 금·토·일·공휴일 10:30~20:30 (롯데백화점 부산본점 지하1층 Kinetic Stage 팝업스토어 기준)',
    useFee: '기본 무료 (테마열차 기념 QR승차권만 유료)',
    program: '부산역 광장 포토존 / 부산역·범내골역·전포역·광안역·센텀시티역 5개 역 포켓몬카드게임 전시 및 스탬프랠리(경품 교환) / 전포역·광안역·센텀시티역·스타필드시티 명지점·토이저러스 부산점 "포켓몬스쿨"(카드게임 배우기) / 도시철도 1·2호선 포켓몬 테마열차(주야간 테마) 운행 / 테마버스 운행 / 롯데백화점 내 포켓몬 팝업스토어',
    summary: '포켓몬 시리즈 30주년을 기념해 포켓몬코리아가 부산광역시 및 지역 기관들과 협업해 여는 대규모 이벤트입니다. "포켓몬 느긋느긋 바캉스"를 테마로, 부산역을 시작으로 도시철도·시내버스 등 대중교통 곳곳을 포켓몬으로 꾸며 도시 전체를 여행하듯 즐길 수 있습니다.'
  },
  {
    title: '제1회 사이언스 로드 in 태종대',
    startDate: '2026-07-17',
    endDate: '2026-07-17',
    place: '태종대 일원',
    image: 'https://www.visitbusan.net/upload_data/board_data/BBS_0000009/178398813163467.jpg',
    homepage: 'http://www.goongle.org/board/board_vertical_view.php?&idx=2873&bid=event&sv=&sw=&page=1',
    category: '행사',
    sponsor1: '부산과학문화거점센터(부산광역시, 부산과학기술협의회 공동운영)',
    sponsor2: '부산관광공사',
    playTime: '10:00~17:00 (우천 시 다음날 진행)',
    useFee: '무료',
    program: '태종대 순환도로(4.3km) 무료 셔틀버스 운행 / 태종대 전망대(반딧불이와 빛의 과학 체험) / 영도등대(빛으로 전하는 바다 신호 퀴즈쇼) / 태종사 입구(수국 색 변화 실험, 블루멜로우 티 체험) 등 3개 체험부스 운영',
    summary: '부산의 명승지 태종대 순환도로를 과학관광길로 재조명하는 첫 시도로, 부산과학문화거점센터가 부산관광공사와 협업해 처음 개최했습니다. 전망대·등대·태종사 입구 3곳에서 과학문화해설사와 함께 지질·빛·생태를 주제로 한 해설과 체험을 즐길 수 있습니다.'
  },
  {
    title: '광안리 M 드론라이트쇼 한국의 멋',
    startDate: '2026-07-18',
    endDate: '2026-07-18',
    place: '부산광역시 수영구 광안해변로 219',
    image: 'https://cdn.prod.website-files.com/6669214a59db5176f76a197e/6a3b44c20473660ab63b2687_2026%EB%85%84%20%EA%B4%91%EC%95%88%EB%A6%ACM%EB%93%9C%EB%A1%A0%EB%9D%BC%EC%9D%B4%ED%8A%B8%EC%87%BC_%EC%9C%A0%EB%B9%84%ED%8C%8C%EC%9D%B4_7%EC%9B%94_4%3B5%20size-6.png',
    homepage: 'https://www.gwangallimdrone.co.kr/',
    category: '공연',
    sponsor1: '부산광역시 수영구청',
    playTime: '20:00, 22:00 (하절기 기준, 회당 약 12분, 7월부터 드론 1,100대로 확대)',
    useFee: '무료 (광안리해변 어디서나 관람 가능)',
    summary: '매주 토요일 열리는 상설 드론쇼로, 이번 회차는 "가장 한국스러운 것이 가장 세계적인 것"이라는 콘셉트로 한국 전통의 멋과 미를 세계에 선보이는 무대입니다. 7월부터 드론 규모가 1,100대로 확대되어 한층 웅장해졌습니다.'
  },
  {
    title: '광안리 M 드론라이트쇼 포켓몬 느긋느긋 바캉스 in 광안리',
    startDate: '2026-07-25',
    endDate: '2026-07-25',
    place: '부산광역시 수영구 광안해변로 219',
    image: 'https://cdn.prod.website-files.com/6669214a59db5176f76a197e/6a3b44fa5907ba92335091a5_2026%EB%85%84%20%EA%B4%91%EC%95%88%EB%A6%ACM%EB%93%9C%EB%A1%A0%EB%9D%BC%EC%9D%B4%ED%8A%B8%EC%87%BC_%EC%9C%A0%EB%B9%84%ED%8C%8C%EC%9D%B4_7%EC%9B%94_4%3B5%20size-7.png',
    homepage: 'https://www.gwangallimdrone.co.kr/',
    category: '공연',
    sponsor1: '부산광역시 수영구청',
    sponsor2: '포켓몬코리아',
    playTime: '20:00, 22:00 (하절기 기준, 회당 약 12분, 드론 약 1,100대 투입)',
    useFee: '무료 (광안리해변 어디서나 관람 가능)',
    summary: '포켓몬 30주년을 기념해 수영구청과 포켓몬코리아가 협업한, 포켓몬을 소재로는 국내 최초로 선보이는 드론쇼입니다. 7월 공연의 대미를 장식하는 회차로, 전 세계적으로 사랑받는 포켓몬을 통해 관람객들에게 동심과 추억을 선사합니다.'
  },
  {
    title: '민락수변공원 반려동물 문화축제',
    startDate: '2026-07-24',
    endDate: '2026-07-26',
    place: '수영구 민락수변공원 일원(GATE 1 ~ GATE 3)',
    image: 'https://ecimg.cafe24img.com/pg2720b82469806068/blueys31/pet/Poster_01.jpg',
    homepage: 'https://pettherock.co.kr/index.html',
    category: '축제',
    sponsor1: '부산광역시 수영구청',
    playTime: '17:00~21:00',
    useFee: '무료',
    program: '반려동물 동반 요가, 펫션쇼, 장기자랑, 어질리티 체험, 사진 콘테스트, 스탬프 투어, 반려동물 포토존, 전문가 강연·토크콘서트 등',
    summary: '2026 민락수변공원 반려동물 문화축제는 반려인, 비반려인이 반려동물과 함께 서로 교감하고 즐거움을 경험하는 축제입니다.'
  },
  {
    title: 'KIMA WEEK 2026 제14회 대한민국 국제해양레저위크',
    startDate: '2026-07-30',
    endDate: '2026-08-02',
    place: '다대포해수욕장',
    image: 'http://www.kimaweek.org/se2/upload/02147bd0f33e84adb077da3589103979_1782792433_6809.png',
    homepage: 'http://www.kimaweek.org/html/index.html',
    category: '행사',
    sponsor1: '해양수산부, 부산광역시',
    sponsor2: '(사)한국해양레저네트워크',
    playTime: '15:00~20:00',
    useFee: '키마비치 이벤트존은 무료 / 요트·서핑·SUP 등 해양레저 체험은 유료(홀릭잼 앱 사전예약)',
    program: '키마비치 이벤트존(인디밴드 공연, 해변 비치요가, 포토존 등 복합문화공간, 남녀노소 무료 참여) / 해양레저체험페스티벌(요트·서핑·크루즈·패들보드 등 전문강사 지도하 체험, 사전신청 필요)',
    summary: '2013년부터 매년 열리는 국내 최대 규모의 국제 해양레저 축제로, 해양수산부와 부산광역시가 주최합니다. 다대포해수욕장을 중심으로 한 무료 문화공간 "키마비치"와, 요트·서핑 등을 직접 체험할 수 있는 유료 프로그램으로 구성됩니다.'
  },
  {
    title: '2026부산국제사진제',
    startDate: '2026-07-29',
    endDate: '2026-08-18',
    place: '부산항국제전시컨벤션센터, 사상인디스테이션',
    image: 'https://bipf.kr/2026/assets/img/about-3.jpg',
    homepage: 'https://bipf.kr/2026/',
    category: '행사',
    sponsor1: '부산국제사진제 조직위원회',
    playTime: '10:00~18:00',
    useFee: '일부 전시 유료',
    program: '주제: "사람 人" / 주제전 「Being Human, 다시 사람」, 국제교류전 「World_SEQUENCES」, 국제청년작가전 「시대공감」, 국제 오픈콜 「Hello Human」 등 사진 전시',
    summary: '"사람 人"을 주제로 국내외 사진작가들의 작품을 소개하는 국제 사진 축제로, 인간 존엄이라는 인류 보편의 가치를 다양한 전시를 통해 이야기합니다.'
  },
  {
    title: '2026 세계도서관정보대회(WLIC)',
    startDate: '2026-08-10',
    endDate: '2026-08-13',
    place: '벡스코, 부산지역 주요 도서관 및 문화시설',
    image: 'https://www.kla.kr/api/editor/images/2319', 
    homepage: 'https://2026.ifla.org/',
    category: '행사',
    sponsor1: '국제도서관협회연맹(IFLA), 부산광역시',
    useFee: '홈페이지 참조',
    program: '세계 최대 규모 도서관·정보 분야 국제 학술대회, 문화 프로그램',
    summary: '국제도서관협회연맹(IFLA)이 주최하는 세계 최대 규모의 도서관 행사로, 2006년 서울 개최 이후 20년 만에 한국에서 다시 열립니다. 150여 개국 5,000여 명의 도서관·정보 전문가가 모여 디지털 전환 시대 도서관의 역할과 미래를 논의합니다.'
  },
{
    title: '2026 월드 스마트시티 엑스포',
    startDate: '2026-09-09',
    endDate: '2026-09-11',
    place: '벡스코 제1전시장',
    image: 'https://worldsmartcityexpo.com/share/img/sub/img01_1_1_1_v26.jpg',
    homepage: 'https://worldsmartcityexpo.com',
    category: '행사',
    sponsor1: '국토교통부, 과학기술정보통신부, 부산광역시',
    sponsor2: '한국토지주택공사, 한국수자원공사, 벡스코, 스마트도시협회',
    playTime: '9월 9일(수)-10:00~17:00, 9월 10일(수)-10:00~17:00, 9월 11일(목)-10:00~16:00',
    useFee: '무료(온라인으로 사전등록을 하거나, 행사장에 방문하여 현장등록)',
    program: '스마트 도시건설, 인프라, 교통, 에너지, 환경, 라이프&헬스케어 관련 기업 전시 / 개막행사 / 국제 컨퍼런스 / WSCE 어워즈 / 기업 발표회 등',
    summary: '올해 10주년을 맞은 아시아·태평양 지역 최대 규모의 스마트시티 국제행사입니다. "Beyond Smart City, Into AI City(스마트시티를 넘어, AI 도시로)"를 슬로건으로, 정부의 AI 대전환 정책에 맞춰 "K-AI 시티" 정책을 처음 선보입니다. 지난해 부산 개최 때는 참관객 약 4만 3천 명, 해외 54개국이 참여했습니다.'
  },
  // {
  //   title: '2026 K-ICT WEEK in BUSAN',
  //   startDate: '2026-09-09',
  //   endDate: '2026-09-11',
  //   place: '벡스코 제1전시장 3홀',
  //   image: '',
  //   homepage: 'https://ictweek.kr/en/html/00_main/',
  //   category: '행사',
  //   sponsor1: '과학기술정보통신부, 부산광역시, 부산광역시교육청',
  //   sponsor2: '정보통신산업진흥원, 부산정보산업진흥원, 벡스코, 전자신문',
  //   playTime: '상세 일정 추후 공개',
  //   useFee: '홈페이지 참조',
  //   program: 'AI KOREA, CLOUD EXPO, IT EXPO 3개 전시회 동시개최, 클라우드 및 헬스테크 컨퍼런스, 바이어 상담회 등'
  // },
  {
    title: '부산국제공연예술제[B.P.A.F]',
    startDate: '2026-09-18',
    endDate: '2026-09-20',
    place: '금정구 온천천 및 부산대학로',
    image: '',                      //나중에 정보 추가
    homepage: 'https://www.gjfac.org/gjfac/template.php?midx=402',  //나중에 정보 추가
    category: '축제',
    sponsor1: '(재)금정문화재단',
    playTime: '프로그램별 상이',                                      //나중에 정보 추가
    useFee: '무료 (야외 공모작 및 초청작 중심)',
    program: '국내·외 우수 거리공연 실연, 아트마켓, 전시 및 부대프로그램 운영',
    summary: '금정구민을 비롯한 시민 문화가 공존하는 온천천을 배경으로 매년 9월 열리는 부산 대표 거리공연예술제입니다. 서커스, 퍼포먼스, 음악극 등 다양한 장르의 국내외 거리예술 작품을 무료로 만나볼 수 있습니다.'
  },

];